# -*- coding: utf-8 -*-
"""动作表唯一来源（single source of truth）
============================================
本文件由 `_build_registry.py` 生成，**请勿手改生成区**（上部 ACTIONS / PARAM_BASELINE）。
要改动作，先改 `_build_registry.py` 里的元数据，再重跑：

    py _build_registry.py

下游全部从这里派生，不再各写一份：
  - editor_server.ACTIONS            （编辑器动作下拉，保持原样）
  - script_translator.ACTION_SCHEMA  （转译提示词 / 校验器合法动作名）
  - script_translator.ACTION_PARAMS  （参数归一与默认值）
  - script_generator 生成提示词的动作表 + 能力卡
  - script_generator._valid_action_names()

字段说明：
  action   规范动作名（别名归一后）
  desc     一句话说明（进提示词）
  when     什么时候用（能力卡「何时用」，见 _build_registry.py 的 _WHEN）
  snippet  3~6 行片段示例（能力卡，见 _SNIPPET）
  script_ok 是否允许出现在 AI 创作的剧本里
  editor    是否出现在编辑器动作下拉里
  primary   文本剧本 `[动作] 参数` 里那个「参数」叫什么
"""

import json

# ============================================================
# 生成区（勿手改）
# ============================================================

ACTIONS = [{'action': '打开聊天',
  'category': '聊天',
  'icon': '💬',
  'desc': '从聊天列表点击进入指定会话',
  'params': [{'key': '联系人', 'label': '联系人名称', 'type': 'text', 'placeholder': '如：小明', 'default': ''}],
  'when': '进入某个会话；实时对白的第一步',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '联系人'},
 {'action': '我方打字',
  'category': '聊天',
  'icon': '⌨️',
  'desc': '手机键盘动画打字 + 回车发送',
  'params': [{'key': '内容', 'label': '要输入的内容', 'type': 'textarea', 'default': ''}],
  'when': '我方发出去的**真实聊天话术**（口语，不要说教）',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '打字不发',
  'category': '聊天',
  'icon': '✍️',
  'desc': '键盘上打出「给观众看的教学字幕/博弈内容」（如 礼貌开场、学以致用）但**不发送**——这是教学视频最精彩的卖点，观众看的就是这段字被打出来再删掉的过程。三段写法：`[打字不发] 字幕 | 停留秒 | '
          '对方插话1；插话2`；插话支持全部消息格式（按行首标记路由）：`[对方表情] 短名`贴纸、`[对方图片] 短名`图片、`[对方链接] 标题 | 封面 | 来源`链接卡、`[对方emoji] '
          '微笑`3D黄脸、`[对方语音] 5`语音条、`[对方转账] 金额 | 备注`转账卡；无标记=纯文字（文字里的 [微笑] 按内嵌 emoji 渲染）',
  'params': [{'key': '内容', 'label': '要输入的内容', 'type': 'textarea', 'default': ''},
             {'key': '停留', 'label': '停留秒数', 'type': 'number', 'default': '1.5'}],
  'when': '键盘上打出「给观众看的技巧字幕/博弈内容」但不发送，随后删掉——全片最精彩的卖点；第 1 段就是这段字幕',
  'snippet': ['[打字不发] 故意否定 引起注意 | 0.5 | 你这人什么意思？！',
              '[删除文字] -1',
              '[我方打字] 我猜你今天又被谁惹了',
              '# 三段语义：第1段=键盘上打给观众看的教学字幕/博弈内容（不发送）；第2段=停留秒数；第3段=对方边看你打字边发的插话',
              '# 插话支持全部消息格式（表情包/图片/链接/emoji/语音/转账，行首标记路由）：',
              '[打字不发] 学以致用 | 1.0 | 你不准想太多；[对方表情] 勃然小怒猫咪；[对方图片] 洱海日落；[对方语音] 5',
              '[删除文字] -1'],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '删除文字',
  'category': '聊天',
  'icon': '⌫',
  'desc': '按退格键删除输入框字符（-1 = 清空）',
  'params': [{'key': '数量', 'label': '删除字符数（-1 清空）', 'type': 'text', 'default': '-1'}],
  'when': '清空输入框；紧跟 [打字不发] 之后',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '数量'},
 {'action': '对方正在输入',
  'category': '聊天',
  'icon': '⏳',
  'desc': '聊天头部显示「对方正在输入...」',
  'params': [{'key': '秒数', 'label': '显示秒数', 'type': 'number', 'default': '1.2'}],
  'when': '对方回话前的「对方正在输入…」（不要每条都用）',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '秒数'},
 {'action': '对方发消息',
  'category': '聊天',
  'icon': '📨',
  'desc': '对方逐字打字（含打错退回）后以左侧白气泡上屏，不再是瞬间复制',
  'params': [{'key': '内容', 'label': '消息内容', 'type': 'textarea', 'default': ''},
             {'key': '头像',
              'label': '对方头像（可空）',
              'type': 'text',
              'placeholder': '如：/images/peer/peer_avatar.jpg',
              'default': ''}],
  'when': '对方回复；允许连发 2~3 条制造真实感',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '对方后台发消息',
  'category': '聊天',
  'icon': '📩',
  'desc': '给当前不在看的会话投递对方消息，画面不变，仅刷新该会话在主页的预览+未读角标（返回主页可看到）；内容以 [图片] 开头时变成图片气泡',
  'params': [{'key': '联系人', 'label': '目标会话联系人', 'type': 'text', 'default': ''},
             {'key': '内容', 'label': '消息内容（[图片] 开头=图片消息）', 'type': 'textarea', 'default': ''},
             {'key': '图片', 'label': '配图路径（图片消息用，可空）', 'type': 'text', 'default': ''},
             {'key': '头像', 'label': '对方头像（可空）', 'type': 'text', 'default': ''},
             {'key': '发送者', 'label': '群聊发送者名（可空）', 'type': 'text', 'default': ''},
             {'key': '置顶', 'label': '来消息置顶', 'type': 'select', 'options': ['是', '否'], 'default': '是'}],
  'when': '别的会话来了消息：画面不变，只刷主页预览 + 未读角标',
  'snippet': ['[对方后台发消息] 联系人=香儿 | 内容=在忙吗 | 置顶=是'],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '后台消息队列',
  'category': '聊天',
  'icon': '📬',
  'desc': '装载一批后台消息并立刻在后台发出去：执行到这一行时，队列里每条消息马上投递给对应会话，刷新主页预览+未读角标，之后打开该会话即可看到（不再按秒/步延迟）',
  'params': [{'key': '数据',
              'label': 'JSON 数组，形如 [{联系,内容,头像,置顶}]',
              'type': 'textarea',
              'placeholder': '[{"联系":"香儿","内容":"图片怎么发您"}]',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '数据'},
 {'action': '查看图片',
  'category': '聊天',
  'icon': '🔍',
  'desc': '点开一张图片放大查看：全屏放大动画 + 手抖停留 + 自动关闭',
  'params': [{'key': '图片',
              'label': '图片路径',
              'type': 'text',
              'placeholder': '如：/images/peer/peer_avatar.jpg',
              'default': ''},
             {'key': '停留', 'label': '停留秒数（可空）', 'type': 'number', 'default': '0.3'},
             {'key': '焦点', 'label': '放大位置 x,y（可空）', 'type': 'text', 'placeholder': '如 0.35,0.4', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '图片'},
 {'action': '返回主页',
  'category': '导航',
  'icon': '🏠',
  'desc': '切回聊天列表主页（转场动画结束后默认再停留 0.3s）',
  'params': [{'key': '停留', 'label': '转场后主页等待秒数（默认可空）', 'type': 'number', 'default': '0.3'}],
  'when': '结束当前会话，回到聊天列表',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': None},
 {'action': '切换Tab',
  'category': '导航',
  'icon': '🧭',
  'desc': '点击底部 Tab',
  'params': [{'key': 'Tab',
              'label': 'Tab 名称',
              'type': 'select',
              'options': ['微信', '通讯录', '发现', '我'],
              'default': '微信'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': 'Tab'},
 {'action': '隐藏键盘',
  'category': '导航',
  'icon': '🙈',
  'desc': '收起手机键盘',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '进入朋友圈',
  'category': '朋友圈',
  'icon': '📖',
  'desc': '从发现页进入朋友圈',
  'params': [],
  'when': '开出第二条叙事线：朋友圈',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': None},
 {'action': '打开对方主页',
  'category': '个人主页',
  'icon': '👤',
  'desc': '点对方消息头像 → 推入「对方个人资料页」（头像/昵称/微信号/地区/朋友资料/朋友圈缩略图/视频号/发消息）',
  'params': [{'key': '对方',
              'label': '人设名（可空，留空用场景里配置的对方）',
              'type': 'text',
              'placeholder': '如：餐车老板娘·吴遂卿',
              'default': ''}],
  'when': '点她头像看她资料页（制造话题、看她的世界）',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '对方'},
 {'action': '进入对方朋友圈',
  'category': '个人主页',
  'icon': '🌅',
  'desc': '点资料页「朋友圈」行 → 右滑推入对方朋友圈（全屏封面 + 昵称头像签名 + 动态列表）',
  'params': [],
  'when': '翻她的朋友圈找话题',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': None},
 {'action': '打开对方设置',
  'category': '个人主页',
  'icon': '⚙️',
  'desc': '点资料页右上角「…」推入联系人设置页（编辑备注/设置权限/推荐给朋友/星标/加入黑名单/投诉/删除联系人，深色样式复刻参考视频）',
  'params': [{'key': '对方',
              'label': '人设名（可空，留空用场景里配置的对方）',
              'type': 'text',
              'placeholder': '如：餐车老板娘·吴遂卿',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '对方'},
 {'action': '加入黑名单',
  'category': '个人主页',
  'icon': '🚫',
  'desc': '拉黑全过程动画：拨「加入黑名单」开关变绿 → 底部弹起确认弹窗（确定/取消）→ 点确定弹窗收起 → 中央「正在加载」加载动画，复刻参考视频全过程',
  'params': [{'key': '确认', 'label': '弹窗点哪个按钮', 'type': 'select', 'options': ['确定', '取消'], 'default': '确定'},
             {'key': '加载秒', 'label': '「正在加载」显示秒数', 'type': 'number', 'default': '1.4'},
             {'key': '停留', 'label': '结束停留秒数', 'type': 'number', 'default': '0.8'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '确认'},
 {'action': '移出黑名单',
  'category': '个人主页',
  'icon': '✅',
  'desc': '把已拉黑的联系人移出黑名单：开关关掉 → 确认弹窗（文案为移出版本）→ 确定 → 「正在加载」加载动画',
  'params': [{'key': '确认', 'label': '弹窗点哪个按钮', 'type': 'select', 'options': ['确定', '取消'], 'default': '确定'},
             {'key': '加载秒', 'label': '「正在加载」显示秒数', 'type': 'number', 'default': '1.4'},
             {'key': '停留', 'label': '结束停留秒数', 'type': 'number', 'default': '0.8'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '确认'},
 {'action': '返回上一页',
  'category': '个人主页',
  'icon': '↩️',
  'desc': '对方朋友圈 → 对方资料页 → 聊天页（iOS 推出转场）',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '闪回聊天',
  'category': '个人主页',
  'icon': '⚡',
  'desc': '硬切回聊天界面：默认自动「闪黑」——黑幕淡入→黑屏下瞬间隐藏「我的朋友圈」或「对方主页/朋友圈」并完成 Tab 切换/进会话→黑幕淡出，把真实微信没有的跨画面跳变盖在黑幕下；闪白=是 走旧版闪白，闪黑=否 '
          '裸硬切；「回到」填联系人时，闪回后直接进该会话',
  'params': [{'key': '回到', 'label': '闪回后进入的会话（可空=只回聊天列表）', 'type': 'text', 'default': ''},
             {'key': '闪黑', 'label': '闪黑过渡（是/否，默认是；闪白=是 时自动失效）', 'type': 'text', 'default': '是'},
             {'key': '闪白', 'label': '旧版：切镜瞬间叠一帧白（是/否）', 'type': 'text', 'default': ''},
             {'key': '停留', 'label': '停留秒数（可空）', 'type': 'text', 'default': ''}],
  'when': '从主页/朋友圈一帧切回聊天（剪辑感，像视频切镜）；默认自动闪黑过渡',
  'snippet': ['[进入朋友圈]',
              '[点赞] 2',
              '[闪回聊天] 回到=香儿    ← 默认自动闪黑：黑幕盖住跳变，切黑再亮起已在聊天',
              '[闪回聊天] 回到=香儿 | 闪黑=否    ← 不要黑幕的裸硬切（旧版行为）'],
  'script_ok': True,
  'editor': True,
  'primary': '回到'},
 {'action': '编辑对方资料',
  'category': '个人主页',
  'icon': '🧩',
  'desc': '整体替换「对方」的资料与朋友圈（昵称/微信号/地区/头像/封面/签名/朋友圈缩略图/视频号/动态全部可配）；动态里加 video 即为视频动态（朋友圈里显示播放角标，可点开全屏播放）',
  'params': [{'key': '数据',
              'label': '预设名 / JSON 对象 / .json 路径',
              'type': 'textarea',
              'placeholder': '{"name":"吴遂卿","wxid":"LSDH-WSQ","area":"广东 '
                             '佛山","gender":0,"avatar":"/images/peer/peer_avatar.jpg","signature":"随心随性","cover":"/images/peer/peer_cover.jpg","posts":[{"date":"10 '
                             '6月","images":["/images/peer/peer_p1.jpg"],"text":"偶尔玩下 蛮好"},{"date":"08 '
                             '6月","video":"/videos/_test.mp4","cover":"/images/peer/peer_v1.jpg","text":"随手拍的海"}]}',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '数据'},
 {'action': '向下滚动',
  'category': '朋友圈',
  'icon': '⬇️',
  'desc': '自然滚动指定像素（我的朋友圈 / 对方朋友圈均可）',
  'params': [{'key': '像素', 'label': '像素', 'type': 'number', 'default': '300'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '像素'},
 {'action': '向上滚动',
  'category': '朋友圈',
  'icon': '⬆️',
  'desc': '向上滚动指定像素（我的朋友圈 / 对方朋友圈均可）',
  'params': [{'key': '像素', 'label': '像素', 'type': 'number', 'default': '300'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '像素'},
 {'action': '滚动到',
  'category': '朋友圈',
  'icon': '↕️',
  'desc': '把朋友圈滚到顶部或底部（对方朋友圈优先，没开时用我的朋友圈）',
  'params': [{'key': '位置', 'label': '位置', 'type': 'select', 'options': ['底部', '顶部'], 'default': '底部'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '位置'},
 {'action': '点开图片',
  'category': '朋友圈',
  'icon': '🔍',
  'desc': '点开朋友圈动态里的配图全屏查看（对方朋友圈优先，没开时用我的朋友圈）；序号写「2」=第2条第1张，写「2,3」=第2条第3张',
  'params': [{'key': '序号', 'label': '第几条动态,第几张图（可空，默认 1,1）', 'type': 'text', 'placeholder': '如：2,3', 'default': '1'},
             {'key': '停留', 'label': '停留秒数（可空=默认）', 'type': 'number', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '序号'},
 {'action': '播放视频',
  'category': '朋友圈',
  'icon': '▶️',
  'desc': '点开朋友圈视频全屏播放（停留后自动关闭）；留空「视频」则点开当前打开的朋友圈里第 N 个视频动态（对方朋友圈优先，没开时用我的朋友圈）',
  'params': [{'key': '视频',
              'label': '视频地址（可空，留空=点开朋友圈里的视频）',
              'type': 'text',
              'placeholder': '如：/videos/_test.mp4',
              'default': ''},
             {'key': '序号', 'label': '第几个视频动态（留空视频时生效）', 'type': 'number', 'default': '1'},
             {'key': '停留', 'label': '播放停留秒数（可空=按视频时长）', 'type': 'number', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '视频'},
 {'action': '点赞',
  'category': '朋友圈',
  'icon': '👍',
  'desc': '复刻真机点赞：弹出「···」两格菜单（♥赞/💬评论）→ 点「赞」→ 菜单收起 + 点赞条弹出；「序号」留空 = 最后一条动态',
  'params': [{'key': '序号', 'label': '第几条动态（留空=最后一条）', 'type': 'number', 'default': ''}],
  'when': '给朋友圈动态点赞（该动态必须先存在）',
  'snippet': ['[进入朋友圈]', '[点赞]', '[闪回聊天] 回到|香儿'],
  'script_ok': True,
  'editor': True,
  'primary': '序号'},
 {'action': '评论',
  'category': '朋友圈',
  'icon': '💬',
  'desc': '复刻真机评论：弹出「···」菜单点「评论」→ 输入条随键盘滑入 → 键盘动画打字 → 点「发送」后评论弹进点赞/评论条',
  'params': [{'key': '内容', 'label': '评论内容', 'type': 'textarea', 'default': ''},
             {'key': '序号', 'label': '第几条动态（留空=最后一条）', 'type': 'number', 'default': ''}],
  'when': '给朋友圈动态评论：弹菜单→点评论→键盘打字→发送',
  'snippet': ['[进入朋友圈]', '[评论] 这也太好看了吧'],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '发朋友圈',
  'category': '朋友圈',
  'icon': '✏️',
  'desc': '发表文字朋友圈（键盘打字 + 发表上屏）',
  'params': [{'key': '内容', 'label': '朋友圈文案', 'type': 'textarea', 'default': ''},
             {'key': '图片', 'label': '配图路径（可空）', 'type': 'text', 'default': ''}],
  'when': '我方发一条朋友圈动态（之后可点赞/评论它）',
  'snippet': ['[发朋友圈] 今天的风很舒服 | 好显身材的连衣裙'],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '编辑朋友圈',
  'category': '朋友圈',
  'icon': '🖼️',
  'desc': '重建「我的朋友圈」动态（作者/文案/配图/视频/点赞/评论全可配）；也支持对象形式 {me:{...}, posts:[...]} 一次同时改主页资料',
  'params': [{'key': '数据',
              'label': 'JSON 数组、{me,posts} 对象或 .json 文件路径',
              'type': 'textarea',
              'placeholder': '[{"author":"香儿","text":"...","images":["/images/peer/peer_p1.jpg"],"likes":["香儿"]},{"author":"香儿","text":"随手拍的海","video":"/videos/_test.mp4","cover":"/images/peer/peer_v1.jpg"}]',
              'default': ''}],
  'when': '预设「我的朋友圈」动态列表（点赞/评论前必须先有动态）',
  'snippet': ['[编辑朋友圈] [{"author":"我","text":"晚上去吃了火锅","images":["美食"],"likes":["香儿"]}]'],
  'script_ok': True,
  'editor': True,
  'primary': '数据'},
 {'action': '编辑我的资料',
  'category': '个人资料',
  'icon': '🧑',
  'desc': '编辑「我」的主页资料：昵称 / 头像 / 朋友圈封面 / 个性签名（主页列表、通讯录、朋友圈同步更新）',
  'params': [{'key': '数据',
              'label': 'JSON 对象或 .json 文件路径',
              'type': 'textarea',
              'placeholder': '{"name":"小明","avatar":"/images/avatar/2_20260831_184618_874.jpg","bg":"/images/peer/peer_cover.jpg","signature":"填坑小能手"}',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '数据'},
 {'action': '设置头像',
  'category': '个人资料',
  'icon': '🪪',
  'desc': '修改头像（所有位置即时更新）',
  'params': [{'key': '图片',
              'label': '头像图片路径',
              'type': 'text',
              'placeholder': '如：/images/peer/peer_avatar.jpg',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '图片'},
 {'action': '设置背景',
  'category': '个人资料',
  'icon': '🖼️',
  'desc': '修改朋友圈封面背景',
  'params': [{'key': '图片',
              'label': '背景图片路径',
              'type': 'text',
              'placeholder': '如：/images/avatar/IMG_0491_20260903_144508_035.png',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '图片'},
 {'action': '修改昵称',
  'category': '个人资料',
  'icon': '🏷️',
  'desc': '修改我的昵称（主页列表、通讯录、朋友圈同步更新）',
  'params': [{'key': '昵称', 'label': '新昵称', 'type': 'text', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '昵称'},
 {'action': '修改签名',
  'category': '个人资料',
  'icon': '✒️',
  'desc': '修改我的个性签名（同步到通讯录 / 我的资料）',
  'params': [{'key': '签名', 'label': '个性签名', 'type': 'text', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '签名'},
 {'action': '编辑主页',
  'category': '主页',
  'icon': '🏠',
  'desc': '按数据重建聊天列表主页：支持私聊/群聊/未读/免打扰，可一次配多个会话，之后用「打开聊天」逐个进入',
  'params': [{'key': '数据',
              'label': 'JSON 数组或 .json 文件路径',
              'type': 'textarea',
              'placeholder': '[{"name":"小明","text":"明天下午方便通个电话吗","avatar":"/images/avatar/2_20260831_184618_874.jpg"},{"group":"周末聚餐讨论群","text":"今晚八点开会","members":["小明","小红"],"newMsgCount":2}]',
              'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '数据'},
 {'action': '发送图片',
  'category': '聊天',
  'icon': '🖼️',
  'desc': '我方在聊天里发送一张图片（真实气泡）；「打开」为是则发送后自动点开放大查看再关闭',
  'params': [{'key': '图片',
              'label': '图片路径',
              'type': 'text',
              'placeholder': '如：/images/peer/peer_avatar.jpg',
              'default': ''},
             {'key': '打开', 'label': '是否点开查看', 'type': 'select', 'options': ['否', '是'], 'default': '否'},
             {'key': '停留', 'label': '查看停留秒数（可空）', 'type': 'number', 'default': '0.3'},
             {'key': '焦点', 'label': '放大位置 x,y（可空）', 'type': 'text', 'placeholder': '如 0.35,0.4', 'default': ''}],
  'when': '我方发图；关键词只能写【可用素材】清单里的短名',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '图片'},
 {'action': '对方发图片',
  'category': '聊天',
  'icon': '🖼️',
  'desc': '对方发送一张图片；「打开」为是则上屏后自动点开放大查看再关闭',
  'params': [{'key': '图片',
              'label': '图片路径',
              'type': 'text',
              'placeholder': '如：/images/avatar/2_20260831_184618_874.jpg',
              'default': ''},
             {'key': '打开', 'label': '是否点开查看', 'type': 'select', 'options': ['否', '是'], 'default': '否'},
             {'key': '停留', 'label': '查看停留秒数（可空）', 'type': 'number', 'default': '0.3'},
             {'key': '焦点', 'label': '放大位置 x,y（可空）', 'type': 'text', 'placeholder': '如 0.35,0.4', 'default': ''}],
  'when': '对方发图（一律选身材/穿搭类）',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '图片'},
 {'action': '发送表情',
  'category': '聊天',
  'icon': '🖼️',
  'desc': '我方发表情贴纸（小尺寸贴纸气泡）；配图选哪张就发哪张',
  'params': [{'key': '表情',
              'label': '表情图片路径',
              'type': 'text',
              'placeholder': '如：/images/myemoji/xxx.png',
              'default': ''},
             {'key': '发送后', 'label': '发完后底部面板去向', 'type': 'select', 'options': ['自动', '键盘', '收起'], 'default': '自动'}],
  'when': '我方发贴纸表情包（78×78 小气泡）',
  'snippet': ['[发送表情] 害羞猫咪'],
  'script_ok': True,
  'editor': True,
  'primary': '表情'},
 {'action': '对方表情',
  'category': '聊天',
  'icon': '🖼️',
  'desc': '对方发来表情贴纸；配图选哪张就上屏哪张',
  'params': [{'key': '表情',
              'label': '表情图片路径',
              'type': 'text',
              'placeholder': '如：/images/myemoji/xxx.png',
              'default': ''}],
  'when': '对方发贴纸表情包',
  'snippet': ['[对方发消息] 在忙吗', '[对方表情] 害羞猫咪         ← 对方回一张贴纸表情（比文字更松弛）'],
  'script_ok': True,
  'editor': True,
  'primary': '表情'},
 {'action': '对方后台发表情',
  'category': '聊天',
  'icon': '🖼️',
  'desc': '给未打开的会话投递对方表情，刷新主页预览/角标',
  'params': [{'key': '联系人', 'label': '目标会话联系人', 'type': 'text', 'default': ''},
             {'key': '表情',
              'label': '表情图片路径',
              'type': 'text',
              'placeholder': '如：/images/myemoji/xxx.png',
              'default': ''}],
  'when': '未打开的会话里，对方发来一张表情',
  'snippet': ['[对方后台发表情] 联系人=香儿 | 表情=害羞猫咪', '                        ← 画面不切走，只刷主页预览 + 未读角标'],
  'script_ok': True,
  'editor': True,
  'primary': '表情'},
 {'action': '发送emoji',
  'category': '聊天',
  'icon': '😀',
  'desc': '我方发送 emoji 小表情（微信新版 3D 表情共 108 个：黄脸+手势/物品/企鹅，弹笑脸面板→逐个点选→发送，全真机动画）。表情写名称/别名/编号，多个用逗号分隔。全部可用名称及含义见 '
          '/images/wxemoji3d/names.json（编号 1~110=面板显示顺序）。★ 也可以内嵌：把 [名称] 直接写进 [我方打字]/[打字不发] 的文本里（如 '
          '太开心了[大笑]），随文字一起上屏，不必单独占一行；内嵌写法认 names.json 里的名称与别名',
  'params': [{'key': '表情',
              'label': 'emoji 名称/编号',
              'type': 'text',
              'placeholder': '如：害羞 / 呲牙 / 3 / 3,5,8 / 随机',
              'default': ''},
             {'key': '发送后', 'label': '发完后底部面板去向', 'type': 'select', 'options': ['自动', '键盘', '收起'], 'default': '自动'}],
  'when': '我方发微信 3D 黄脸小表情：先弹笑脸面板→逐个点选→一次发送。也可以不单独占行：直接把 [名称] 写进文本内容里内嵌上屏',
  'snippet': ['[发送emoji] 捂脸            ← 弹笑脸面板→点选→发送',
              '[发送emoji] 3,5,8 | 18:22   ← 多个表情逐个进输入框后一次发出',
              '[我方打字] 太开心了[大笑]   ← 内嵌写法：文本里直接 [名称]，随文字一起上屏'],
  'script_ok': True,
  'editor': True,
  'primary': '表情'},
 {'action': '对方emoji',
  'category': '聊天',
  'icon': '😀',
  'desc': '对方发来 emoji 小表情（直接上屏左侧气泡）。表情写名称/编号/随机，可用名称见 /images/wxemoji3d/names.json。★ 也可以内嵌：把 [名称] 直接写进 '
          '[对方发消息]/[对方后台发消息] 的内容里（如 是嘛[捂脸]），随文字一起上屏，不必单独占一行；内嵌写法认 names.json 里的名称与别名',
  'params': [{'key': '表情', 'label': 'emoji 名称/编号', 'type': 'text', 'placeholder': '如：捂脸 / 5 / 随机', 'default': ''}],
  'when': '对方发 3D 黄脸小表情（直接上屏，不弹面板）。也可以不单独占行：把 [名称] 写进 [对方发消息] 的文本里内嵌上屏',
  'snippet': ['[对方emoji] 害羞', '[对方发消息] 是嘛[捂脸]     ← 内嵌写法：文本里直接 [名称]，无需单独一行'],
  'script_ok': True,
  'editor': True,
  'primary': '表情'},
 {'action': '发送语音',
  'category': '聊天',
  'icon': '🎙️',
  'desc': '我方发送语音消息（时长决定波形长短）',
  'params': [{'key': '秒数', 'label': '语音秒数', 'type': 'number', 'default': '3'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '秒数'},
 {'action': '对方语音',
  'category': '聊天',
  'icon': '🎙️',
  'desc': '对方发送语音消息',
  'params': [{'key': '秒数', 'label': '语音秒数', 'type': 'number', 'default': '3'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '秒数'},
 {'action': '撤回我的消息',
  'category': '聊天',
  'icon': '↩️',
  'desc': '撤回我方最后一条消息，显示系统提示',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '对方撤回消息',
  'category': '聊天',
  'icon': '↩️',
  'desc': '对方撤回一条消息，显示系统提示',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '转发消息',
  'category': '聊天',
  'icon': '🔁',
  'desc': '我方转发一条消息（转发：内容）',
  'params': [{'key': '内容', 'label': '转发内容', 'type': 'textarea', 'default': ''}],
  'when': '转发一条消息（内容带「转发：」前缀）',
  'snippet': ['[转发消息] 转发：聊天案例解析（必看）'],
  'script_ok': True,
  'editor': True,
  'primary': '内容'},
 {'action': '切换底部面板',
  'category': '聊天',
  'icon': '🎛️',
  'desc': '直接切换聊天页底部面板（键盘/表情/更多/收起），不退回聊天底部；输入栏 230ms 对称 S 曲线直接位移，旧面板下滑、新面板同帧上滑（复刻参考视频「微信聊天框三个界面切换.mp4」）',
  'params': [{'key': '面板', 'label': '目标面板', 'type': 'select', 'options': ['键盘', '表情', '更多', '收起'], 'default': '键盘'},
             {'key': '停留', 'label': '切换后停留秒数（可空，默认 0.3）', 'type': 'number', 'default': '0.3'}],
  'when': '聊天中段直接切一下表情/更多面板再收起：真实感最强的新动作',
  'snippet': ['[切换底部面板] 表情 | 0.8      ← 聊天中段切到表情面板再收起', '[切换底部面板] 收起 | 0.4'],
  'script_ok': True,
  'editor': True,
  'primary': '面板'},
 {'action': '面板切换序列',
  'category': '聊天',
  'icon': '🎞️',
  'desc': '按给定节奏「一口气」连续切换底部三面板（键盘/表情/更多/收起），精确定时复刻参考视频的整段切换；定时在浏览器端完成，节奏可逐帧对齐。序列每项 = {面板, 停留}：立刻切到「面板」，停留 N 秒再执行下一项。',
  'params': [{'key': '序列',
              'label': '序列（JSON 数组，元素含 面板/停留）',
              'type': 'textarea',
              'default': '[{"面板":"收起","停留":1.83},{"面板":"键盘","停留":1.75},{"面板":"表情","停留":1.25},{"面板":"更多","停留":1.7},{"面板":"收起","停留":1.65},{"面板":"表情","停留":1.65},{"面板":"键盘","停留":1.4},{"面板":"更多","停留":1.5}]'}],
  'when': '一口气按既定节奏连切三面板（复刻参考视频的整段节奏）',
  'snippet': ['[面板切换序列] [{"面板":"表情","停留":0.9},{"面板":"更多","停留":1.1},{"面板":"收起","停留":0.6}]'],
  'script_ok': True,
  'editor': True,
  'primary': '序列'},
 {'action': '打开转账面板',
  'category': '聊天',
  'icon': '➕',
  'desc': '点聊天输入栏「+」弹出功能面板（照片/转账/红包等，对齐参考图1）',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '转账金额',
  'category': '聊天',
  'icon': '💰',
  'desc': '真实转账流程：功能面板→金额页输金额/说明→转账→6位密码→橙色转账卡片',
  'params': [{'key': '接收人', 'label': '接收人（聊天对象名）', 'type': 'text', 'default': ''},
             {'key': '金额', 'label': '转账金额', 'type': 'text', 'default': '50.00'},
             {'key': '备注', 'label': '备注（可空）', 'type': 'text', 'default': ''},
             {'key': '密码', 'label': '支付密码（6位数字）', 'type': 'text', 'default': '123456'}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '金额'},
 {'action': '转账',
  'category': '聊天',
  'icon': '💰',
  'desc': '我方发送一笔转账（绿色转账卡片：谁 + 金额 + 备注）',
  'params': [{'key': '接收人', 'label': '接收人（聊天对象名）', 'type': 'text', 'default': ''},
             {'key': '金额', 'label': '转账金额', 'type': 'text', 'default': '50.00'},
             {'key': '备注', 'label': '备注（可空）', 'type': 'text', 'default': ''}],
  'when': '我方转账（默认关闭；仅当规则明确要求时才用）',
  'snippet': ['[手机状态栏] 转账', '[转账] 接收人=香儿 | 金额=520.00 | 备注=别熬夜'],
  'script_ok': True,
  'editor': True,
  'primary': '金额'},
 {'action': '对方转账',
  'category': '聊天',
  'icon': '💰',
  'desc': '对方发来一笔转账（左侧转账卡片）',
  'params': [{'key': '接收人', 'label': '接收人', 'type': 'text', 'default': ''},
             {'key': '金额', 'label': '转账金额', 'type': 'text', 'default': '50.00'},
             {'key': '备注', 'label': '备注（可空）', 'type': 'text', 'default': ''}],
  'when': '对方发来转账（默认关闭；仅当规则明确要求时才用）',
  'snippet': ['[对方转账] 接收人=我 | 金额=200.00 | 备注=请你喝奶茶'],
  'script_ok': True,
  'editor': True,
  'primary': '金额'},
 {'action': '打开转账详情',
  'category': '聊天',
  'icon': '🧾',
  'desc': '点击对方转账卡片，打开转账详情页（右滑推入，深色页面）',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '接收转账',
  'category': '聊天',
  'icon': '✅',
  'desc': '在转账详情页点「收款」：「正在加载」toast 后瞬时切换为已收款（绿色对勾+已存入零钱+零钱通推广行）',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '关闭转账详情',
  'category': '聊天',
  'icon': '↩️',
  'desc': '点返回箭头，转账详情页右滑退出回聊天页',
  'params': [],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': None},
 {'action': '手机状态栏',
  'category': '聊天',
  'icon': '📱',
  'desc': '切换状态栏场景：转账=参考视频状态栏（03:14+灵动岛微信绿标+录屏红点），默认=恢复 18:36',
  'params': [{'key': '模式', 'label': '模式', 'type': 'select', 'options': ['转账', '默认'], 'default': '转账'}],
  'when': '把手机状态栏切成参考场景（03:14 + 录屏红点），开场用一次',
  'snippet': ['[手机状态栏] 转账         ← 开场第一行：切成参考视频状态栏'],
  'script_ok': True,
  'editor': True,
  'primary': '模式'},
 {'action': '@成员',
  'category': '聊天',
  'icon': '👥',
  'desc': '在输入框 @ 成员（弹出键盘，内容保留在输入框）',
  'params': [{'key': '昵称', 'label': '成员昵称', 'type': 'text', 'placeholder': '如：小明', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': True,
  'primary': '昵称'},
 {'action': '等待',
  'category': '系统',
  'icon': '⏱️',
  'desc': '自然等待指定秒数',
  'params': [{'key': '秒数', 'label': '等待秒数', 'type': 'number', 'default': '1'}],
  'when': '真正要停一下的地方（整份 7~12 处，不要每句都跟一个）',
  'snippet': [],
  'script_ok': True,
  'editor': True,
  'primary': '秒数'},
 {'action': '闪到对方朋友圈',
  'category': '个人主页',
  'icon': '⚡',
  'desc': '一帧闪进「对方朋友圈」：黑幕淡入→黑屏下瞬时开资料页+朋友圈→黑幕淡出，跳过资料页（真实微信没有这条路径），观感是电影切黑再亮起；「对方」填预设名可顺手切人设（可空=沿用当前人设）',
  'params': [{'key': '对方', 'label': '联系人预设名（可空）', 'type': 'text', 'default': ''},
             {'key': '闪黑', 'label': '闪黑过渡（是/否，默认是）', 'type': 'text', 'default': '是'},
             {'key': '停留', 'label': '切完后停留秒数（可空）', 'type': 'text', 'default': ''}],
  'when': '从聊天一帧闪进她的朋友圈（黑幕过渡，跳过资料页——真实微信没有这条路径）',
  'snippet': ['[打开聊天] 香儿', '[闪到对方朋友圈]             ← 一帧黑幕闪进她的朋友圈（跳过资料页）', '[闪回聊天] 回到=香儿        ← 再一帧黑幕闪回聊天，一对剪辑切镜'],
  'script_ok': True,
  'editor': True,
  'primary': '对方'},
 {'action': '我方发链接',
  'category': '聊天',
  'icon': '🔗',
  'desc': '我方在聊天里发送一张链接卡片（公众号文章/分享链接）：标题文字自动换行，字多撑高卡片；右侧方形缩略图（可空）；左下角来源名可替换（默认「恋爱技巧」）',
  'params': [{'key': '标题', 'label': '链接标题（必填，可自动换行）', 'type': 'text', 'default': ''},
             {'key': '图片', 'label': '卡片缩略图（可空）', 'type': 'text', 'default': ''},
             {'key': '来源', 'label': '左下角来源名（可空默认恋爱技巧）', 'type': 'text', 'default': '恋爱技巧'},
             {'key': '时间', 'label': '时间分隔条（如 18:22，可空）', 'type': 'text', 'default': ''}],
  'when': '我方转发一张链接卡片',
  'snippet': [],
  'script_ok': True,
  'editor': False,
  'primary': '标题'},
 {'action': '对方发链接',
  'category': '聊天',
  'icon': '🔗',
  'desc': '对方发送一张链接卡片（气泡在左），参数含义同「我方发链接」',
  'params': [{'key': '标题', 'label': '链接标题（必填）', 'type': 'text', 'default': ''},
             {'key': '图片', 'label': '卡片缩略图（可空）', 'type': 'text', 'default': ''},
             {'key': '来源', 'label': '左下角来源名（可空默认恋爱技巧）', 'type': 'text', 'default': '恋爱技巧'},
             {'key': '时间', 'label': '时间分隔条（如 18:22，可空）', 'type': 'text', 'default': ''}],
  'when': '对方发来链接卡片（历史块里最好用的钩子）',
  'snippet': [],
  'script_ok': True,
  'editor': False,
  'primary': '标题'},
 {'action': '应用场景',
  'category': '场景',
  'icon': '🎬',
  'desc': '套用场景预设（联系人列表 + 人物资料 + 朋友圈 + 聊天底稿）',
  'params': [{'key': '场景', 'label': '场景名', 'type': 'text', 'default': ''},
             {'key': '数据', 'label': 'JSON 数据（可空）', 'type': 'textarea', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': False,
  'primary': '场景'},
 {'action': '编辑会话',
  'category': '场景',
  'icon': '🧵',
  'desc': '按数据重建某个会话的全部消息（清空并重放）',
  'params': [{'key': '数据', 'label': 'JSON 数组 / 对象', 'type': 'textarea', 'default': ''}],
  'when': '',
  'snippet': [],
  'script_ok': False,
  'editor': False,
  'primary': '数据'}]

# 现有 ACTION_PARAMS 的行为基线（派生时优先沿用，避免默认值漂移）
PARAM_BASELINE = {'打开聊天': {'联系人': None},
 '我方打字': {'内容': None, '插话': None, '时间': None},
 '打字不发': {'内容': None, '停留': 1.5, '插话': None},
 '删除文字': {'数量': -1},
 '对方正在输入': {'秒数': 1.2},
 '对方发消息': {'内容': None, '头像': None, '时间': None},
 '对方后台发消息': {'联系人': None, '内容': None, '图片': None, '头像': None, '发送者': None, '置顶': None, '时间': None},
 '后台消息队列': {'数据': None, '时间': None},
 '查看图片': {'图片': None, '打开': None, '停留': None, '焦点': None, '放大倍率': None},
 '返回主页': {},
 '切换Tab': {'Tab': '微信'},
 '隐藏键盘': {},
 '进入朋友圈': {},
 '打开对方主页': {'对方': None},
 '进入对方朋友圈': {},
 '打开对方设置': {'对方': None},
 '加入黑名单': {'确认': '确定', '加载秒': 1.4, '停留': 0.8},
 '移出黑名单': {'确认': '确定', '加载秒': 1.4, '停留': 0.8},
 '返回上一页': {},
 '闪回聊天': {'回到': None, '闪黑': '是', '闪白': None, '停留': None},
 '编辑对方资料': {'数据': None, 'data': None, '对方': None},
 '向下滚动': {'像素': 300},
 '向上滚动': {'像素': 300},
 '滚动到': {'位置': '底部'},
 '点开图片': {'序号': '1', '停留': None},
 '播放视频': {'视频': None, '序号': 1, '停留': None},
 '点赞': {'序号': None},
 '评论': {'内容': None, '序号': None},
 '发朋友圈': {'内容': None, '图片': None},
 '编辑朋友圈': {'数据': None},
 '编辑我的资料': {'数据': None},
 '设置头像': {'图片': None},
 '设置背景': {'图片': None},
 '修改昵称': {'昵称': None},
 '修改签名': {'签名': None},
 '编辑主页': {'数据': None},
 '发送图片': {'图片': None, '打开': None, '停留': None, '焦点': None, '放大倍率': None, '时间': None},
 '对方发图片': {'图片': None, '打开': None, '停留': None, '焦点': None, '放大倍率': None, '时间': None},
 '发送表情': {'表情': None, '发送后': '自动'},
 '对方表情': {'表情': None},
 '对方后台发表情': {'联系人': None, '表情': None, '时间': None},
 '发送emoji': {'表情': None, '发送后': '自动'},
 '对方emoji': {'表情': None},
 '发送语音': {'秒数': 3},
 '对方语音': {'秒数': 3},
 '撤回我的消息': {},
 '对方撤回消息': {},
 '转发消息': {'内容': None},
 '切换底部面板': {'面板': '键盘', '停留': 0.3},
 '面板切换序列': {'序列': '[{"面板":"收起","停留":1.83},{"面板":"键盘","停留":1.75},{"面板":"表情","停留":1.25},{"面板":"更多","停留":1.7},{"面板":"收起","停留":1.65},{"面板":"表情","停留":1.65},{"面板":"键盘","停留":1.4},{"面板":"更多","停留":1.5}]'},
 '打开转账面板': {},
 '转账金额': {'接收人': None, '金额': None, '备注': None, '密码': None},
 '转账': {'接收人': None, '金额': None, '备注': None},
 '对方转账': {'接收人': None, '金额': None, '备注': None},
 '打开转账详情': {},
 '接收转账': {},
 '关闭转账详情': {},
 '手机状态栏': {'模式': '转账'},
 '@成员': {'昵称': None},
 '等待': {'秒数': 1},
 '闪到对方朋友圈': {'对方': None, '闪黑': '是', '停留': None},
 '我方发链接': {'标题': None, '图片': None, '来源': '恋爱技巧', '时间': None},
 '对方发链接': {'标题': None, '图片': None, '来源': '恋爱技巧', '时间': None},
 '应用场景': {'场景': None, 'scene': None, '数据': None, 'data': None},
 '编辑会话': {'数据': None, 'data': None}}

# 生成区结束

# ============================================================
# 派生接口（下游只调这些）
# ============================================================

PRIMARY_KEY_FALLBACK = "内容"


def by_name() -> dict:
    return {a["action"]: a for a in ACTIONS}


def names() -> set:
    return {a["action"] for a in ACTIONS}


def editor_actions() -> list:
    """给 editor_server.ACTIONS 用（保持编辑器 UI 不变）。"""
    return [a for a in ACTIONS if a.get("editor", True)]


def script_actions() -> list:
    """允许出现在 AI 创作剧本里的动作。"""
    return [a for a in ACTIONS if a.get("script_ok", True)]


def schema() -> list:
    """给 script_translator.ACTION_SCHEMA 用：{action, desc, params:[{key,label}]}。"""
    out = []
    for a in ACTIONS:
        out.append({
            "action": a["action"],
            "desc": a["desc"],
            "params": [{"key": p["key"], "label": p.get("label", p["key"])}
                       for p in a.get("params") or []],
        })
    return out


def _coerce(default, dtype):
    if default in (None, ""):
        return None
    if dtype == "number":
        try:
            return float(default)
        except (TypeError, ValueError):
            return default
    return str(default)


def param_defaults() -> dict:
    """给 script_translator.ACTION_PARAMS 用：动作 -> {参数名: 缺省值}。

    已有动作沿用 PARAM_BASELINE（保持原行为不变）；新动作按各自的参数表推导，
    这样「以前没进过参数表」的 8 个新动作也能正常归一、吃默认值。
    """
    out = {}
    for a in ACTIONS:
        name = a["action"]
        if name in PARAM_BASELINE:
            out[name] = dict(PARAM_BASELINE[name])
            continue
        derived = {}
        for p in a.get("params") or []:
            derived[p["key"]] = _coerce(p.get("default"), p.get("type"))
        out[name] = derived
    # 参数基线里有、但动作表里没有的（历史遗留），一并保留，别让老剧本失效
    for name, d in PARAM_BASELINE.items():
        out.setdefault(name, dict(d))
    return out


def primary_param(action: str):
    """文本剧本 `[动作] 参数` 里那个「参数」的字段名；无参数动作返回 None。"""
    a = by_name().get(action)
    if not a:
        return None
    p = a.get("primary")
    if p:
        return p
    first = (a.get("params") or [{}])[0].get("key")
    return first if first not in ("数据", "data") else None


def capability_cards(only=None) -> list:
    """能力卡：{action, when, snippet, desc}。新功能必须靠它才可能被用出来。"""
    out = []
    for a in ACTIONS:
        if not a.get("script_ok", True):
            continue
        if only is not None and a["action"] not in only:
            continue
        if not (a.get("when") and a.get("snippet")):
            continue
        out.append({"action": a["action"], "when": a["when"],
                    "snippet": list(a.get("snippet") or []), "desc": a.get("desc", "")})
    return out


def to_json() -> str:
    return json.dumps({"actions": ACTIONS}, ensure_ascii=False, indent=1)
