# -*- coding: utf-8 -*-
"""
微信小表情候选图集构建
=====================
把 `微信图标\小表情` 里的表情 PNG（用于键盘候选条「小表情」装饰）复制到前端静态目录
`vue-WeChat/public/images/wxemoji/`，并生成 `enhance/wxemoji_map.js`：

  window.__WX_WXEMOJI = {
    list : [ {src, id}, ... ],        // 候选条装饰池（全部图，轮换出现）
    words: { "开心": "/images/wxemoji/wx_1.png", ... }   // 词 -> 对应小表情图（语义命中）
  }

供 enhance/keyboard.js 在候选条里混入微信小表情图，并在初始化时预热这些图，
避免候选条首帧闪图/卡顿。

用法：
    py build_wxemoji.py            # 复制图片 + 生成 wxemoji_map.js
"""
import json
import os
import re
import shutil

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT, "微信图标", "小表情")
OUT_DIR = os.path.join(ROOT, "vue-WeChat", "public", "images", "wxemoji")
JS_OUT = os.path.join(ROOT, "enhance", "wxemoji_map.js")
EXTS = (".png", ".jpg", ".jpeg", ".webp", ".gif")

# 词 -> 小表情图（按文件名里的数字编号对应）。编号来自源文件名「小表情 (N).png」。
# 语义命中优先级高于 __WX_EMOJI（苹果 emoji），打字命中这些词时优先上微信小表情图。
# 已逐张人工核对编号对应含义；拿不准的（如流汗吐舌/紫心）不列入，仅留在装饰池轮换。
CURATED_WORDS = {
    # (编号, [词...]) —— 编号 = 图片同名 wx_<编号>.png
    1: ["开心", "大笑", "哈哈", "笑"],                       # 呲牙大笑
    15: ["喜欢", "爱你", "好喜欢", "超喜欢"],                # 爱心眼
    52: ["吐", "恶心", "反胃"],                              # 呕吐
    55: ["冷", "好冷", "冻"],                                # 冻僵
    62: ["酷", "帅", "得意"],                                # 墨镜
    92: ["生气", "愤怒", "恼火"],                            # 愤怒
    95: ["无语", "死了", "服了", "完蛋"],                    # 骷髅
    121: ["比心", "心动"],                                   # 闪亮爱心
    138: ["满分", "干得好", "一百"],                          # 一百分
    145: ["炸", "爆炸", "气炸"],                             # 炸弹
    164: ["举手", "等一下", "停", "举爪"],                    # 举手
    188: ["好的", "可以", "没问题", "行"],                   # OK
    236: ["你", "说的就是你", "那个"],                       # 手指
}


def _image_id(name: str):
    """从「小表情 (N).png」提取编号 N；无法解析返回 None。"""
    m = re.search(r"\((\d+)\)", name)
    return int(m.group(1)) if m else None


def main():
    if not os.path.isdir(SRC_DIR):
        print(f"找不到源目录：{SRC_DIR}")
        return 1
    files = [f for f in os.listdir(SRC_DIR) if f.lower().endswith(EXTS)]
    if not files:
        print(f"源目录没有图片：{SRC_DIR}")
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)
    list_entries = []
    id_to_src = {}
    for f in files:
        fid = _image_id(f)
        if fid is None:
            print(f"  [跳过] 文件名不含编号：{f}")
            continue
        web = f"wx_{fid}.png"
        dst = os.path.join(OUT_DIR, web)
        if not os.path.isfile(dst):
            shutil.copyfile(os.path.join(SRC_DIR, f), dst)
        rel = "/images/wxemoji/" + web
        list_entries.append({"src": rel, "id": fid})
        id_to_src[fid] = rel

    list_entries.sort(key=lambda e: e["id"])
    words = {}
    for fid, ws in CURATED_WORDS.items():
        src = id_to_src.get(fid)
        if not src:
            print(f"  [缺图] 词映射对应编号 {fid} 不在图集里，跳过。")
            continue
        for w in ws:
            words[w] = src

    js = ("/* AUTO-GENERATED by build_wxemoji.py — 微信小表情候选图集"
          "（候选条装饰池 + 词->图装饰映射） */\n"
          "window.__WX_WXEMOJI = " + json.dumps(
              {"list": list_entries, "words": words}, ensure_ascii=False) + ";\n")
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(js)

    print(f"已复制 {len(list_entries)} 张到 {OUT_DIR}")
    print(f"已生成 {JS_OUT}")
    print(f"  装饰池 {len(list_entries)} 张；词->图映射 {len(words)} 条")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
