# -*- coding: utf-8 -*-
"""
苹果 emoji 图集下载 + 生成键盘表情联想映射
=========================================
读取 enhance/emoji_map.json（词 -> emoji），对每个 emoji：
  1. 计算其 Unicode 码点（如 😄=1f604、❤️=2764-fe0f），作为文件名；
  2. 从开源 Apple emoji 图集（emoji-datasource-apple，jsDelivr CDN）下载
     `img/apple/64/<codepoint>.png` 到 vue-WeChat/public/images/emoji/；
  3. 下载失败或文件已存在则不重复下载，缺图时前端回退为文字 emoji。

并生成 enhance/emoji_map.js：
  window.__WX_EMOJI = { "开心": {"code":"1f604","emoji":"😄"}, ... }
供 enhance/keyboard.js 在候选条做「表情联想」用。

用法：
    py fetch_apple_emoji.py            # 下载全部映射 emoji + 生成 emoji_map.js
    py fetch_apple_emoji.py --check    # 只检查哪些缺图（不下载）
"""
import json
import os
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = os.path.dirname(os.path.abspath(__file__))
MAP_PATH = os.path.join(ROOT, "enhance", "emoji_map.json")
JS_OUT = os.path.join(ROOT, "enhance", "emoji_map.js")
IMG_DIR = os.path.join(ROOT, "vue-WeChat", "public", "images", "emoji")

# jsDelivr 托管的 emoji-datasource-apple（Apple Color Emoji PNG）
CDN_TPL = "https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.1.2/img/apple/64/{code}.png"
# 单次下载超时：失败项快速跳过，避免整批卡住
_TIMEOUT = 8


def _codepoints(emoji: str) -> str:
    """返回 emoji 的码点字符串（如 😄->'1f604'；❤️->'2764-fe0f'）。"""
    return "-".join(f"{ord(c):x}" for c in emoji)


def _download(code: str) -> bool:
    """下载单个 emoji PNG。成功或已存在返回 True。"""
    fp = os.path.join(IMG_DIR, code + ".png")
    if os.path.isfile(fp):
        return True
    url = CDN_TPL.format(code=code)
    try:
        # 用标准库 urllib，避免额外依赖；带 UA 防 CDN 拒绝
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=_TIMEOUT) as resp:
            data = resp.read()
        if not data:
            return False
        os.makedirs(IMG_DIR, exist_ok=True)
        with open(fp, "wb") as fh:
            fh.write(data)
        return True
    except Exception as exc:                        # noqa: BLE001
        print(f"  [下载失败] {code}: {exc}")
        return False


def main():
    if not os.path.isfile(MAP_PATH):
        print(f"未找到 {MAP_PATH}，请确认 emoji_map.json 存在。")
        return 1
    with open(MAP_PATH, "r", encoding="utf-8") as fh:
        raw = json.load(fh)
    word_emoji = {k: v for k, v in raw.items() if not k.startswith("_") and isinstance(v, str)}
    check_only = "--check" in sys.argv

    fail = []
    js_entries = {}
    total = len(word_emoji)
    ok = 0
    for i, (word, emoji) in enumerate(word_emoji.items(), 1):
        code = _codepoints(emoji)
        js_entries[word] = {"code": code, "emoji": emoji}
        exists = os.path.isfile(os.path.join(IMG_DIR, code + ".png"))
        if check_only:
            if not exists:
                fail.append(code)
            else:
                ok += 1
            continue
        if _download(code):
            ok += 1
        else:
            fail.append(code)
        if i % 10 == 0:
            print(f"  进度 {i}/{total}")

    # 写 emoji_map.js（无论是否断网都生成，供 keyboard.js 用；缺图时前端回退文本 emoji）
    js = ("/* AUTO-GENERATED by fetch_apple_emoji.py — 词 -> 苹果 emoji 表情联想映射 */\n"
          "window.__WX_EMOJI = " + json.dumps(js_entries, ensure_ascii=False) + ";\n")
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(js)

    if check_only:
        print(f"检查完成：{ok} 个已存在，{len(fail)} 个缺图。")
        if fail:
            print("  缺图：" + ", ".join(fail[:20]))
        return 0

    print(f"下载完成：成功 {ok}/{total}；生成 {JS_OUT}。")
    if fail:
        print(f"  失败 {len(fail)} 个（会回退文字 emoji）：" + ", ".join(fail[:20]))
    return 0


if __name__ == "__main__":
    import urllib.request
    sys.exit(main())